---
type: yml
auth:
  sign_key: hello

mysql:
  host: localhost
  port: 3308
  db_name: "gameapp_db"
  username: "gameapp"
  password: "gameappt0lk2o20"

http_server:
  port: 1986

redis:
  host: localhost
  port: 6380
  password: ""
  db: 0

matching_service:
  waiting_timeout: "2m"

presence_service:
  expiration_time: 60m
  prefix: presence

scheduler:
  match_waited_user_interval_in_seconds: 30
